
import { createClient } from '@supabase/supabase-js'
import type { Tenant } from './types';

// The 'Database' type is generated by Supabase CLI.
// We are defining a partial type here manually to make progress.
// TODO: Replace with `import { Database } from './database.types';`
export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: Tenant;
        Insert: Omit<Tenant, 'id'>;
        Update: Partial<Tenant>;
      }
    }
  }
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase URL and/or Anon Key are not defined in .env')
}

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
