
import { createClient } from '@supabase/supabase-js'
import type { Tenant, Product } from './types';

// The 'Database' type is generated by Supabase CLI.
// We are defining a partial type here manually to make progress.
// TODO: Replace with `import { Database } from './database.types';`
export type Database = {
  public: {
    Tables: {
      tenants: {
        Row: {
          tenant_id: number;
          created_at: string;
          name: string;
          responsibleParty: string;
          brn: string | null;
          vat: string | null;
          mobile: string;
          address: string | null;
        };
        Insert: Omit<Tenant, 'tenant_id' | 'created_at'>;
        Update: Partial<Omit<Tenant, 'tenant_id' | 'created_at'>>;
      },
      products: {
        Row: {
            id: string;
            name: string;
            price: number;
            tenant_id: number;
            created_at: string;
        };
        Insert: Omit<Product, 'id' | 'created_at'>;
        Update: Partial<Omit<Product, 'id' | 'created_at'>>;
      }
    }
    Functions: {}
    Enums: {}
  }
}

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseAnonKey) {
  // A console.error is more appropriate here than throwing an error,
  // as the app can still function in a limited capacity without Supabase.
  console.error('Supabase URL and/or Anon Key are not defined in .env. The app will run in offline-only mode.')
}

export const supabase = supabaseUrl && supabaseAnonKey ? createClient<Database>(supabaseUrl, supabaseAnonKey) : null;
