-- 0001_create_tenants.sql

-- Enable Realtime for the tenants table
-- alter publication supabase_realtime add table tenants;

-- Create the tenants table
create table if not exists tenants (
    tenant_id bigint generated by default as identity primary key,
    created_at timestamptz with time zone default now() not null,
    name text not null,
    "responsibleParty" text not null,
    brn text null,
    vat text null,
    mobile text not null,
    address text null
);

-- Add comments to the table and columns
comment on table tenants is 'Stores information about each tenant or vendor.';
comment on column tenants.tenant_id is 'Unique identifier for each tenant.';
comment on column tenants.created_at is 'Timestamp of when the tenant was created.';
comment on column tenants.name is 'The business name of the tenant.';
comment on column tenants."responsibleParty" is 'The name of the person responsible for the tenant.';
comment on column tenants.brn is 'Business Registration Number.';
comment on column tenants.vat is 'VAT Registration Number.';
comment on column tenants.mobile is 'Contact mobile number for the tenant.';
comment on column tenants.address is 'Physical address of the tenant.';
