-- supabase/migrations/0004_create_orders_and_items.sql

-- Create the orders table
create table orders (
  id text primary key,
  created_at timestamptz default now() not null,
  tenant_id bigint not null references tenants(tenant_id) on delete restrict,
  cashier_id uuid references cashiers(id) on delete set null,
  total numeric not null,
  vat numeric not null,
  subtotal numeric not null
);

alter table orders enable row level security;

-- Create the order_items table
create table order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  product_id uuid not null references products(id) on delete restrict,
  quantity int not null,
  price numeric not null
);

alter table order_items enable row level security;